spring:
  datasource:
    url: jdbc:h2:mem:feeder;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    open-in-view: false
  flyway:
    enabled: false

mqtt:
  broker-url: ${MQTT_BROKER_URL:tcp://152.67.43.175:1883}
  username: ${MQTT_USERNAME:}
  password: ${MQTT_PASSWORD:}
  devices: ${MQTT_DEVICES:ALIMENTADOR_1,ALIMENTADOR_2,ALIMENTADOR_3}

server:
  port: ${PORT:8080}

logging:
  level:
    com.wbm.feeder: INFO
